CREATE TABLE [WBApi].[SI]
(
	si_id       INT IDENTITY(1, 1) CONSTRAINT [PK_WBApiSI] PRIMARY KEY CLUSTERED NOT NULL,
	si_name     VARCHAR(25) NOT NULL,
	dt          DATETIME2(0) NOT NULL
)

GO
CREATE UNIQUE NONCLUSTERED INDEX [UQ_WBApiSI_si_name] ON WBApi.SI(si_name) ON [Indexes]